# fly.toml app configuration file generated for management-app-backend on 2025-08-17T00:44:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'management-app-backend'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://0.0.0.0:8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
